Tabernicola\BlogBundle\Entity\Post:
    type: entity
    table: BlogPost
    repositoryClass: Tabernicola\BlogBundle\Entity\PostRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: '128'
        slug:
            type: string
            length: 128
            gedmo:
              slug:
                separator: _
                style: normal
                fields:
                  - title
        content:
            type: text
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
              timestampable:
                on: update
        state:
            type: smallint
    lifecycleCallbacks: {  }
